name: Semantic PR Validation

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  validate:
    name: Validate PR title
    uses: ItsMestro/devtools/.github/workflows/shared-semantic-pr-validation.yml@7cfd271073000d44c117aa9fd5a894e6f212fa1d # main
    permissions:
      pull-requests: read
    secrets: inherit
